### PR TITLE
add the puzzle cube taters

### PR DESCRIPTION
**Pull request by sockfriends**
sdgerg

### CODE REVIEW

**Comment by Restioson** [comment]
This has merge conflicts

**Comment by sockfriends** [comment]
how do i fix it

**Comment by Restioson** [comment]
You can look at the command line instructions at the merge conflicts notification box or in the web editor and resolve the conflicts. There are some resources online about how to deal with merge conflicts.

**Comment by sockfriends** [comment]
i thought i made a fork

**Comment by Restioson** [comment]
You can still get mege conflicts

**Pull request merged**
