### PR TITLE
Tater Advancements

### PR DESCRIPTION
**Pull request by Shnupbups**
Advancements thus far:
My First Tater: Collect your first Tater in your Tater Box.
Tater Hobbyist: Collect 10 Taters in your Tater Box.
Tater Collector: Collect 25 Taters in your Tater Box.
Tater Hoarder: Collect 50 Taters in your Tater Box.
Tater Magnate: Collect every Tater in your Tater Box!
Tiny Potato Says You're Valid: Collect all Pride Taters in your Tater Box.

### CODE REVIEW

**Comment by haykam821** [comment]
Do advancement icons not remap properly in Polymer? Ideally this should be fixed so the Polymer items can be specified directly.

**Comment by Shnupbups** [comment]
> Do advancement icons not remap properly in Polymer? Ideally this should be fixed so the Polymer items can be specified directly.

To be honest, I didn't check. I should do that, shouldn't I...

**Comment by Shnupbups** [comment]
Note: Advancements are not auto-given retroactively! For count-based advancements to update, any tater must be right-clicked with the box (even if it has already been collected), and for specific tater based advancements the specific taters must be right-clicked with the box even if they are already owned. So anyone who already has a Pride Tater must essentially recollect it for it to count towards the advancement. This obviously won't affect brand new players (or new Tater Boxes) who will get them as they should.

**Comment by Shnupbups** [comment]
Someone can make the Advancement tab have a custom background with cursed texture loading via skins on player heads if they want, but it ain't gonna be me

**Pull request merged**
